[install]
auto = true
production = false
save-exact = false
peer = true

[run]
smol = true
env-file = ".env"
preload = ["./src/env-preload.ts"]

# FIX v5.5.23: Re-enabled preload with manual .env loader
# env-preload.ts manually parses .env BEFORE any imports
# This ensures process.env variables are available during module initialization
# Resolves: CORPORATE_PROXY_USER/PASSWORD needed by proxy auth during import