[install]
auto = true
production = false
save-exact = false
peer = true

[run]
smol = true
env-file = ".env"

# FIX v5.5.19: Removed preload to fix environment variable loading order
# Instrumentation now imported explicitly in src/index.ts AFTER .env loads
# Root cause: preload executes BEFORE env-file, causing undefined process.env values